/* Copyright (C) 2020 Chris Piker <chris-piker@uiowa.edu>
 *                    
 * This file is part of das2dlm, an Interactive Data Language (IDL) binding
 * for the das2C library.  IDL is a trademark of Harris Geospatial Solutions,
 * Inc.  The shared object generated by this code may be loaded by main 
 * programs, or other shared objects, even those with closed source licenses.
 *
 * das2dlm is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 2.1 as published
 * by the Free Software Foundation.
 *
 * das2dlm is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 2.1 along with libdas2; if not, see <http://www.gnu.org/licenses/>.
 */

/* ************************************************************************* */
/* API Function, careful with changes! */

#define D2C_DSINFO_MINA 1
#define D2C_DSINFO_MAXA 1
#define D2C_DSINFO_FLAG 0

/*
;+
; FUNCTION:
;  das2c_dsinfo
;
; PURPOSE:
;  Output summary information string about a dataset
;
; CALLING SEQUENCE:
;  Result = das2c_dsinfo(dset)
;
; INPUTS:
;  dset: A DAS2C_DSET structure, as returned by das2c_datasets().
;
; OUTPUT:
;  A multi-line human readable formatted string providing an overview of
;  all organization levels of the dataset.
;
; EXAMPLES:
;  List summary information on the first dataset from query ID 27
;    das2c_dsinfo(27, 0);
;
; MODIFICATION HISTORY:
;  Written by: Chris Piker, 2020-03-10
;-
*/
static IDL_VPTR das2c_api_dsinfo(int argc, IDL_VPTR* argv)
{
	int iQuery = -1;
	int iDs = -1;
	const DasDs* pDs = das2c_arg_to_ds(argc, argv, 0, &iQuery, &iDs);
	
	char sBuf[8192] = {'\0'};
	DasDs_toStr(pDs, sBuf, 8191);
	
	return (IDL_StrToSTRING(sBuf));
}
