/* Copyright (C) 2023 Chris Piker <chris-piker@uiowa.edu>
 *                    
 * This file is part of das2dlm, an Interactive Data Language (IDL) binding
 * for the das2C library.  IDL is a trademark of Harris Geospatial Solutions,
 * Inc.  The shared object generated by this code may be loaded by main 
 * programs, or other shared objects, even those with closed source licenses.
 *
 * das2dlm is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 2.1 as published
 * by the Free Software Foundation.
 *
 * das2dlm is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 2.1 along with libdas2; if not, see <http://www.gnu.org/licenses/>.
 */


/* ************************************************************************* */
/* DAS2C_CRED structure */

/* IDL defininiton of DAS2C_CRED */
static IDL_STRUCT_TAG_DEF DAS2C_CRED_tags[] = {
   {"URL",      0, (void*)IDL_TYP_STRING},
   {"REALM",    0, (void*)IDL_TYP_STRING},
   {"PARAM",    0, (void*)IDL_TYP_STRING},
   {"VALUE",    0, (void*)IDL_TYP_STRING},
   {"HASH",     0, (void*)IDL_TYP_STRING},
   {"VALID",    0, (void*)IDL_TYP_LONG  },
   {0}
};

/* Global struct definition pointer */
static IDL_StructDefPtr DAS2C_CRED_pdef;

static void define_DAS2C_CRED()
{
   DAS2C_CRED_pdef = IDL_MakeStruct("DAS2C_CRED", DAS2C_CRED_tags);
}

/* parallel C structure to use in casts for manipulating IDL struct memory */
typedef struct das2c_cred_data_s{
   IDL_STRING url;
   IDL_STRING realm;
   IDL_STRING param;
   IDL_STRING value;
   IDL_STRING hash;
   IDL_LONG   valid;
} DAS2C_CRED_data;

/* Provide strcasestr so we have it, it's not in the POSIX spec */
const char* loc_strcasestr(const char *haystack, const char *needle)
{
   if(!haystack || !needle) 
      return NULL;

   size_t n = strlen(needle);  /* Length of needle */
   size_t i = 0;               /* Position in needle */
   char c   = '\0';
   while(*haystack != '\0'){

      c = *(needle+i);  

      /* Comparison, assume ASCII encoding so to lowcase a character, add 32 (0x20) */
      if((c == *haystack)||
         ( (c > '@')&&(c < '[')&&((c+0x20) == *haystack) ) ||
         ( (c > '`')&&(c < '{')&&((c-0x20) == *haystack) )
      ){
         /* Matched one */
         ++i;
         if(i == n)
            return haystack - (n - 1);  /* and that was the last one */
      }
      else{
         i = 0; /* match nothing, reset needle */
      }
      ++haystack;
   }
   return NULL;
}

/* ************************************************************************* */
/* API Function, careful with changes! */

#define D2C_CREDS_MINA 0
#define D2C_CREDS_MAXA 4
#define D2C_CREDS_FLAG 0

/*
;+
; FUNCTION:
;   das2_creds
;
; PURPOSE:
;   List credentials sent to servers under matching conditions
;
; CALLING SEQUENCE:
;   struct_ary = das2c_creds()
;   struct_ary = das2c_creds(url)
;   struct_ary = das2c_creds(url, realm)
;   struct_ary = das2c_creds(url, realm, param, value)
;
; OPTIONAL INPUTS:
;   url:     A string providing a URL, or portion of a URL without fragments
;            or query parameters
;
;   realm:   A string providing the RFC-7617 authentication realm string 
;            (see https://httpwg.org/specs/rfc7617.html)
;
;   param:   A query parameter name that must match before the credentials
;             will be sent.
;
;   value:   A query parameter value for the given 'param' above that must
;            match before credentials are sent.
;
; OUTPUT:
;   An array of DAS2C_CRED structures that match the given arguments.  These
;   have the following fields.
;
;     URL:   String   ; The network URL that must match before this credential
;                     ;   would be sent
;
;     REALM: String   ; The realm that must be requested before this
;                     ;   credential would be sent.
;
;     PARAM: String   ; A parameter that must be present in the request before
;                     ; this credential would be sent, may be empty.
;
;     VALUE: String   ; THe value of PARAM that must be present before this
;                     ; credential is sent, may be empty.
;
;     HASH:  String   ; The HTTP basic authentication hash that would be sent
;                     ; to the server.  This is not the password, but is
;                     ; trivially related to it.
;
;     VALID: Long     ; Defaults to 1, reset to 0 if authentication fails when
;                     ; using this credential
;
; EXAMPLES:
;   List all your credentials that are used for U. Iowa Physics Department
;   servers:

;     credentials = das2_cred('physics.uiowa.edu')
;
;   List the credentials that would be sent if accessing a resource
;   that has the HTTP GET parameter 'dataset' with a value of 'Juno/WAV/Survey'
;   to the service at 'https://jupiter.physics.uiowa.edu/das/server':
;     
;     sSrvRoot = 'https://jupiter.physics.uiowa.edu/das/server'
;     sRealm   = 'Juno Magnetospheric Working Group'
;     sDataset = 'Juno/WAV/Survey'
;     cred = das2_cred(sSrvRoot, sRealm, 'dataset', sDataset)
;
; NOTES:
;   For security purposes, das2C does not send your authentication credentials
;   out un-prompted.  Credentials are only sent if the server requests them and 
;   then, only if the URL, Realm and optionally a Parameter in the URL matchs
;   the expected conditions.
;
; MODIFICATION HISTORY:
;   C. Piker, 2023-12-11 - Initial Version
;-
*/
static IDL_VPTR das2c_api_creds(int argc, IDL_VPTR* argv)
{

   /* The arguments are just for filters.  In general we're going to 
      iterate everything */
   const char* sCkUrl = NULL;
   const char* sCkRealm = NULL;
   const char* sCkParam = NULL;
   const char* sCkValue = NULL;

   if((argc > 0)&&(!IDL_NULL(argv[0]))){
      sCkUrl = IDL_VarGetString(argv[0]);
      if((sCkUrl != NULL)&&(*sCkUrl == '\0')){
         sCkUrl = NULL;
      }
   }
   if((argc > 1)&&(!IDL_NULL(argv[1]))){
      sCkRealm = IDL_VarGetString(argv[1]);
      if((sCkRealm != NULL)&&(*sCkRealm == '\0')){
         sCkRealm = NULL;
      }
   }
   if((argc > 2)&&(!IDL_NULL(argv[2]))){
      sCkParam = IDL_VarGetString(argv[2]);
      if((sCkParam != NULL)&&(*sCkParam == '\0')){
         sCkParam = NULL;
      }
   }
   if((argc > 3)&&(!IDL_NULL(argv[3]))){
      sCkValue = IDL_VarGetString(argv[3]);
      if((sCkValue != NULL)&&(*sCkValue == '\0')){
         sCkValue = NULL;
      }
   }

   /* Make sure both param and value are non-null, or both null */
   if( ((sCkParam == NULL)&&(sCkValue != NULL) ) ||
       ((sCkParam != NULL)&&(sCkValue == NULL) ) )
      das2c_IdlMsgExit("Must supply a parameter name when providing a parameter value and vice versa.");

   DasAry* pCreds = g_pDefCred->pCreds; /* This is initialized in das2c.c */

   /* Pass-1, figure out how big to make the output */
   das_credential* pCred = NULL;
   size_t uOut = 0;
   ptrdiff_t aMatch[64] = {0};
   for(ptrdiff_t i = 0; (i < DasAry_size(pCreds)) && (uOut < 64); ++i){
      pCred = (das_credential*)DasAry_getAt(pCreds, vtUnknown, IDX0(i));

      if(sCkUrl && (loc_strcasestr(pCred->sServer, sCkUrl) == NULL))
         continue;
      if(sCkRealm && (loc_strcasestr(pCred->sRealm, sCkRealm) == NULL))
         continue;
      
      // das2.2 hack.  Later for v3.0 we can allow params other then 'dataset'
      if(sCkParam && (loc_strcasestr("dataset", sCkParam) == NULL))
         continue;

      if(sCkValue && (pCred->sDataset[0] != '\0') &&
         (loc_strcasestr(pCred->sDataset, sCkValue) == NULL))
         continue;
      if(sCkValue && (pCred->sDataset[0] == '\0'))
         continue;

      aMatch[uOut] = i;  // It matched
      ++uOut;
   }

   if(uOut == 0) return IDL_GettmpNULL();

   /* make output structure */
   IDL_MEMINT dims = uOut;
   IDL_VPTR pRet;

   DAS2C_CRED_data* pData = (DAS2C_CRED_data*) IDL_MakeTempStruct(
      DAS2C_CRED_pdef,  /* the opaque structure def */
      1,                /* number of dimensions */
      &dims,            /* the size of our dimensions (one dim) */
      &pRet,            /* The actual structure variable */
      TRUE              /* Zero out the array */
   );

   /* Do it again, this time creating output */
   for(size_t u = 0; u < uOut; ++u){
      pCred = (das_credential*)DasAry_getAt(pCreds, vtUnknown, IDX0(aMatch[u]));

      IDL_StrStore(&(pData->url),   pCred->sServer);
      IDL_StrStore(&(pData->realm), pCred->sRealm);
      IDL_StrStore(&(pData->hash),  pCred->sHash);
      pData->valid = pCred->bValid ? 1 : 0;

      if(pCred->sDataset[0] != '\0'){
         IDL_StrStore(&(pData->param), "dataset");
         IDL_StrStore(&(pData->value), pCred->sDataset);
      }
 
      ++pData;
   }

   return pRet;
}

/* ************************************************************************* */
/* API Function, careful with changes! */

#define D2C_CREDSET_MINA 2
#define D2C_CREDSET_MAXA 6
#define D2C_CREDSET_FLAG 0

/*
;+
; FUNCTION:
;  das2c_credset
;
; PURPOSE:
;  Set HTTP Basic Authentication credentials for a specific resources on a server
;
; CALLING SEQUENCE:
;  did_store = das2c_credset(url, realm)
;  did_store = das2c_credset(url, realm, param, value)
;  did_store = das2c_credset(url, realm, param, value, user, password)
;
; INPUTs:
;  url:      A URL string without a fragment or query parameters
;
;  realm:    An authentication realm string.  These are provided by a server
;            when requesting authentication.
;
; OPTIONAL INPUTS:
;   param:    Applies to das2.2.  Set this to 'dataset' to only send this
;             credential when the HTTP GET param 'dataset' is present in 
;             the data request.  May use !NULL to skip this.
;
;   value:    Applies to das2.2, Set value of the 'dataset=' query parameter
;             for which this authentication token will apply.  May use !NULL
;             to skip this.
;
;   user:     Instead of prompting at the terminal (or cmd.exe), provide a
;             username directly.  Required in IDLDE.  See SIDE EFFECTS below.
;
;   password: Instead fo prompting at the terminal (or cmd.exe), provide a
;             clear-text password directly.  Required in IDLDE, See SIDE
;             EFFECTS below.
;
; OUTPUT:
:   Returns the number of stored credentials.  Exits with a message if 
;   there was an error.
;
; SIDE EFFECTS:
;   Normally the underlying das2C library prompts for authentication information
;   at the terminal, on POSIX systems or in a command window on Windows and
;   passwords are not echoed, nor saved in your history.
;
;   Unfortunatly, the IDLDE (IDL Development Enviroment) command window is not
;   a true terminal and so the standard method of entering user names and
;   passwords won't work there.  When called from IDLDE, you must provide the
;   user name and password in the function call.  This means your user name
;   and password *will be saved in your IDL history* file and could be
;   read by any other program that has read access to your home directory!
;
;   Thus, it's best to call this function from a command line IDL session
;   outside of IDLDE.
;
; EXAMPLES:
;   Set the credentials for das3 resource at the terminal:
;     sURL = 'https://tracers.physics.uiowa.edu/stream/source/tr1/ql/mag/bdc_burst'
;     sRealm = 'TRACERS Quicklook'
;     nCreds = das2c_credset(sUrl, sRealm)
;     das2c_credsave()   ; Save currently loaded credentials
;   
;   Set the credentials for a das2 resource at the IDLDE command line:
;     sURL = 'https://planet.physics.uiowa.edu/das/server/'
;     sRealm = 'Realm of Makebelieve'
;     sDataset = 'DE/de-1/pwi_lowrate'
;     sUser = 'drjfever'
;     sPass = 'really~4disco'
;     nCreds = das2c_credsave(sUrl, sRealm, 'dataset', sDataset, sUser, sPass)
;
; MODIFICATION HISTORY:
;   C. Piker, 2023-12-12 - Initial Version
;-
*/
static IDL_VPTR das2c_api_credset(int argc, IDL_VPTR* argv)
{
   if(argc < 2)
       das2c_IdlMsgExit("At a minimum the URL and Realm must be supplied");

   const char* sServer = IDL_VarGetString(argv[0]);
   if((sServer == NULL)||(sServer[0] == '\0'))
      das2c_IdlMsgExit("URL string is empty");  
   
   const char* sRealm  = IDL_VarGetString(argv[1]);
   if((sRealm == NULL)||(sRealm[0] == '\0'))
      das2c_IdlMsgExit("Security realm string is empty");
   
   const char* sParam = NULL;
   if((argc > 2)&&(!IDL_NULL(argv[2]))){
      sParam = IDL_VarGetString(argv[2]);
      /* Restricted for now */
      if(strcmp(sParam, "dataset") != 0)
         das2c_IdlMsgExit("Currently only the param 'dataset' is supported");
   }

   const char* sDataset = NULL;
   if((argc > 3)&&(!IDL_NULL(argv[3])))
      sDataset = IDL_VarGetString(argv[3]);

   char sUser[128] = {'\0'};
   char sPass[128] = {'\0'};
   
   if((argc == 5))
      das2c_IdlMsgExit("Must supply a password when providing a username");
   
   if(argc > 5){
      const char* sTmp = IDL_VarGetString(argv[4]);
      strncpy(sUser, sTmp, 127);
      sTmp = IDL_VarGetString(argv[5]);
      strncpy(sPass, sTmp, 127);
   }
   else{
      /* If no password or username given then run a prompt */
      bool bGotOne = g_pDefCred->prompt(
         sServer, sRealm, sDataset, NULL, sUser, sPass
      );

      if(!bGotOne)
         das2c_IdlMsgExit("Password entry canceled");
   }
   
   int nSize = CredMngr_addUserPass(
      g_pDefCred, sServer, sRealm, sDataset, sUser, sPass
   );

   return IDL_GettmpLong(nSize);
}

/* ************************************************************************* */
/* API Function, careful with changes! */

#define D2C_CREDSAVE_MINA 0
#define D2C_CREDSAVE_MAXA 2
#define D2C_CREDSAVE_FLAG 0

/*
;+
; FUNCTION:
;   das2c_credsave
;
; PURPOSE
;   Save server credentials in an optionally encrypted file
;   
; CALLING SEQUENCE:
;   num_creds = das2c_credsave()
;   num_creds = das2c_credsave(filename)
;   num_creds = das2c_credsave(filename, symetric_key)  ; TODO
;
; OPTIONAL INPUTS:
;   filename:     The full path to the file where cerdentials are saved. If not
;                 provided $HOME/.das2_auth or %USERPROFILE%/.das2_auth is used.
;                 For interoperability, this is the same file name used by das2py
;                 The default location can also be indicated by using !NULL for
;                 this input.
;   
;   symetric_key: A password used to encrypt and decrypt the credentials file.
;                 (This is not yet implemented in das2C, but is documented here
;                  to indicate planned devolpment)
;
; OUTPUT:
;   Returns the number of credentials saved
;
; SIDE EFFECTS:
;   The current credential set in memory is written to the file.  This could
;   overwrite previous entries if das2c_credload() has not been called on the
;   same file.
;
; EXAMPLES:
;   Save authentication tokens and server match criteria in the default 
;   location:
;     nCreds = das2c_credsave()
;   
;   Create and save an auth token in a non-default location:
;     sURL = 'https://planet.physics.uiowa.edu/test/server/'
;     sRealm = 'Realm of Makebelieve'
;     sDataset = 'test/newsource'
;     sUser = 'drjfever'
;     sPass = 'really~4disco'
;     nCreds = das2c_credsave(sUrl, sRealm, sDataset, sUser, sPass)
;     nCreds = das2c_credsave('/home/someone/.test_auth')
;-
*/
static IDL_VPTR das2c_api_credsave(int argc, IDL_VPTR* argv)
{
   const char* sFile = (argc > 0) ? IDL_VarGetString(argv[0]) : NULL;
   const char* sKey =  (argc > 1) ? IDL_VarGetString(argv[1]) : NULL;

   int nCreds = CredMngr_save(g_pDefCred, sKey, sFile);

   if(nCreds < 0)
      das2c_error2idl();
   
   return IDL_GettmpLong(nCreds);
}

/* ************************************************************************* */
/* API Function, careful with changes! */

#define D2C_CREDLOAD_MINA 0
#define D2C_CREDLOAD_MAXA 2
#define D2C_CREDLOAD_FLAG 0

/*
;+
; FUNCTION:
;   das2c_credload
;
; PURPOSE:
;   Load credential and match conditions from an optionally encrypted file
;
; CALLING SEQUENCE:
;   num_creds = das2c_credload()
;   num_creds = das2c_credload(filename)
;   num_creds = das2c_credload(filename, symetric_key)  ; TODO
;
; OPTIONAL INPUTS:
;   filename:     The full path to the file where cerdentials are saved. If not
;                 provided $HOME/.das2_auth or %USERPROFILE%/.das2_auth is used.
;                 For interoperability, this is the same file name used by das2py
;                 The default location can also be indicated by using !NULL for
;                 this input.
;   
;   symetric_key: A password used to encrypt and decrypt the credentials file.
;                 (This is not yet implemented in das2C, but is documented here
;                  to indicate planned devolpment)
;
; OUTPUT:
;   Returns the new number of loaded credentials and match patterns.
;   Since new credentials are merged in with the existing set in 
;   memory, calling this function twice for the same file should
;   always produce the same value for the second output.
;
; EXAMPLES:
:   Determine if a file contains credentials and match condititons not
;   already in memory.
;     nCurCreds = n_elements(das2c_creds())
;     nNewCreds = das2c_credload()
;     print, string(nNewCreds - nCurCreds, format="%d credentials loaded")
;
; MODIFICATION HISTORY:
;   C. Piker 2023-12-12, Initial Version
;-
*/
static IDL_VPTR das2c_api_credload(int argc, IDL_VPTR* argv)
{
   const char* sFile = (argc > 0) ? IDL_VarGetString(argv[0]) : NULL;
   const char* sKey =  (argc > 1) ? IDL_VarGetString(argv[1]) : NULL;

   int nCreds = CredMngr_load(g_pDefCred, sKey, sFile);

   if(nCreds < 0)
      das2c_error2idl();
   
   return IDL_GettmpLong(nCreds);
}
