/* Copyright (C) 2020 Chris Piker <chris-piker@uiowa.edu>
 *                    
 * This file is part of das2dlm, an Interactive Data Language (IDL) binding
 * for the das2C library.  IDL is a trademark of Harris Geospatial Solutions,
 * Inc.  The shared object generated by this code may be loaded by main 
 * programs, or other shared objects, even those with closed source licenses.
 *
 * das2dlm is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 2.1 as published
 * by the Free Software Foundation.
 *
 * das2dlm is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 2.1 along with libdas2; if not, see <http://www.gnu.org/licenses/>.
 */

/* ************************************************************************* */
/* API Function, careful with changes! */

#define D2C_DSINFO_MINA 2
#define D2C_DSINFO_MAXA 2
#define D2C_DSINFO_FLAG 0

/*
;+
; FUNCTION:
;  das2c_dsinfo
;
; PURPOSE:
;  Output summary information string about a dataset
;
; CALLING SEQUENCE:
;  Result = das2c_dsinfo(query_id, ds_index)
;
; INPUTS:
;  query_id: The identification integer for the stored query result as
;            returned by das2c_readhttp() or das2c_queries.
;
;  ds_index: Output information for this dataset number in the query.
;            Most queries will output only a single dataset at index 0,
;            Though common sources such as Juno Waves output more than 1.
;
; OUTPUT:
;  A multi-line human readable formatted string providing an overview of
;  all organization levels of the dataset.
;
; EXAMPLES:
;  List summary information on the first dataset from query ID 27
;    das2c_dsinfo(27, 0);
;
; MODIFICATION HISTORY:
;  Written by: Chris Piker, 2020-03-10
;-
*/
static IDL_VPTR das2c_api_dsinfo(int argc, IDL_VPTR* argv)
{
	char sBuf[1024] = {'\0'};
	int nBuf = 1024;
	
	/* Get/check Query ID */
	int iQueryId = das2c_args_query_id(argc, argv, 0);
	const DasIdlDbEnt* pEnt = das2c_check_query_id(iQueryId);
	
	/* Get/check dataset ID */
	int iDs = das2c_args_ds_id(argc, argv, 1);
	const DasDs* pDs = das2c_check_ds_id(pEnt, iDs);
		
	DasDs_toStr(pDs, sBuf, nBuf);
	
	return (IDL_StrToSTRING(sBuf));
}
