/* Copyright (C) 2020 Chris Piker <chris-piker@uiowa.edu>
 *                    
 * This file is part of das2dlm, an Interactive Data Language (IDL) binding
 * for the das2C library.  IDL is a trademark of Harris Geospatial Solutions,
 * Inc.  The shared object generated by this code may be loaded by main 
 * programs, or other shared objects, even those with closed source licenses.
 *
 * das2dlm is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 2.1 as published
 * by the Free Software Foundation.
 *
 * das2dlm is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 2.1 along with libdas2; if not, see <http://www.gnu.org/licenses/>.
 */

/*
;+
; FUNCTION:
;  das2c_vars
;
; PURPOSE:
;  List the variables present in a physical dimension, in a das2 dataset.
;
; CALLING SEQUENCE:
;  Result = das2c_vars(query_id, ds_index, pdim_index, var)
;
; INPUTS:
;  query_id: The identification integer for the stored query result as
;            returned by das2c_readhttp() or das2c_queries.
;
;  ds_index: The dataset index, often 0.  See das2c_datasets() for details.
;
;  pdim_index: Either the physical dimension index (long), or the dimension's
;            name (string).  For more infor see das2c_physdims().
;
; OPTIONAL INPUTS:
;  var:      Either the role name (string) or the var index (long).  This
;            argument is only required if summary information on a single 
;            variable is desired.
;
;            Variable role names are standardized.  The most common one is
;            'center' which represents the central point of a measurement
;            in a particular physical dimension.  The full set is:
;
;            'center', 'offest', 'min', 'max', 'width', 'mean', 'median',
;            'mode', 'reference', 'offset', 'max_error', 'min_error',
;            'uncertainty',  'std_dev', 'point_spread', 'weight'
;
; OUTPUT:
;  This function returns an array of structures providing an overview of
;  each stored result.  Output structures have the fields:
;
;    'id':     Long     ; The ID number for this variable.  Usage of
;                       ; role names instead of numbers is recommended.
;	
;    'name':   String   ; The role for this variable, for example 'max_error'
;
;    'units':  String   ; The units for values from this variable.
;	
;    'idxmap': 8 Long   ; How to map indices for this variables array into the
;                       ; overall datest index space.  A -1 means array values
;                       ; are degenerate in a given dataset index.
;
;    'shape':  8 Long64 ; The extent of this variable in the dataset indices.
;                       ; Values less than 0 mean the variable is degenerate
;                       ; or ragged in an index.
;
;    'size':   Long64   ; If this variable is directly backed by an array this
;                       ; is the total number of values in that array.  This
;                       ; value is 0 for virtual variables.
;
; EXAMPLES:
;  List summary of all variable roles for the 'time' dimension in dataset 0 of
;  query result 27
;    das2c_vars(27, 0, 'time')
;
;  List summary information of the 'center' variable for 'time' in dataset 0 for
;  query result 27
;    das2c_vars(27, 0, 'time', 'center')
;
;  List summary information for the first variable in the first physical
;  physical dimension of the first datasets, what ever it happens to be.
;    das2c_vars(27, 0, 0, 0)
;
; MODIFICATION HISTORY:
;  Written by: Chris Piker, 2020-03-10
;-
*/
		
/* Output structure definition */
static IDL_STRUCT_TAG_DEF _das2c_var_tags[] = {
	{"id",      NULL,      (void*)IDL_TYP_LONG},
	{"name",    NULL,      (void*)IDL_TYP_STRING},
	{"units",   NULL,      (void*)IDL_TYP_STRING},
	{"idxmap",  g_aShape8, (void*)IDL_TYP_LONG64},
	{"shape",   g_aShape8, (void*)IDL_TYP_LONG64},
	{"size",    NULL,      (void*)IDL_TYP_LONG64},
	{0}
};

typedef struct _das2c_var_sum{
	IDL_LONG   id;
	IDL_STRING name;
	IDL_STRING units;
	IDL_LONG64 idxmap[8];
	IDL_LONG64 shape[8];
	IDL_LONG64 size;
} das2c_VarSummary;

#define D2C_VARS_MINA 1
#define D2C_VARS_MAXA 2
#define D2C_VARS_FLAG 0

static IDL_StructDefPtr g_das2c_pVarSumDef;

static void DAS2C_VAR_def()
{
	g_das2c_pVarSumDef = IDL_MakeStruct("DAS2C_VAR", _das2c_var_tags);
}

static IDL_VPTR das2c_vars(int argc, IDL_VPTR* argv)
{
	return NULL;
}


