/* Copyright (C) 2020 Chris Piker <chris-piker@uiowa.edu>
 *                    
 * This file is part of das2dlm, an Interactive Data Language (IDL) binding
 * for the das2C library.  IDL is a trademark of Harris Geospatial Solutions,
 * Inc.  The shared object generated by this code may be loaded by main 
 * programs, or other shared objects, even those with closed source licenses.
 *
 * das2dlm is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 2.1 as published
 * by the Free Software Foundation.
 *
 * das2dlm is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 2.1 along with libdas2; if not, see <http://www.gnu.org/licenses/>.
 */
 
/*
;+
; FUNCTION:
;  das2c_dsprops
;
; PURPOSE:
;  Get dataset metadata properties
;
; CALLING SEQUENCE:
;  Result = das2c_dsprops(query_id, ds_index, property)
;
; INPUTS:
;  query_id: The identification integer for the stored query result as
;            returned by das2c_readhttp() or das2c_queries.
;
;  ds_index: The dataset index, often 0.  See das2c_datasets() for details.
;
; OPTIONAL INPUTS:
;  property: The name of a specific property
;
; OUTPUT:
;  This function returns an array of structures providing the property or
;  properties of the dataset.  Each structure has the following fields
;
;    'name':   String   ; The name of the property
;
;    'type':   String   ; The intended final data type for the property
;
;    'value':  String   ; A string version of the property value.
;
; EXAMPLES:
;  Get all the properties for dataset 1 from query result 48
;    das2c_dsprops(48, 1)
;
;  Get the title property for dataset 0 from query result 27
;    das2c_dsprops(27, 0, 'title')
;
; MODIFICATION HISTORY:
;  Written by: Chris Piker, 2020-03-10
;-
*/
