MODULE das2c
DESCRIPTION IDL indings for das2c
VERISON  0.2
SOURCE  Das Developers
BUILD_DATE 2020-02-08
FUNCTION DAS2C_QUERIES
FUNCTION DAS2C_DSINFO
FUNCTION DAS2C_DATASETS
FUNCTION DAS2C_PHYSDIMS
FUNCTION DAS2C_VARS
FUNCTION DAS2C_PROPS
FUNCTION DAS2C_ARRAY
FUNCTION DAS2C_FREE
FUNCTION DAS2C_READHTTP 0 IDL_MAXPARAMS
STRUCTURE DAS2C_QUERY
 
