/* Copyright (C) 2020 Chris Piker <chris-piker@uiowa.edu>
 *                    
 * This file is part of das2dlm, an Interactive Data Language (IDL) binding
 * for the das2C library.  IDL is a trademark of Harris Geospatial Solutions,
 * Inc.  The shared object generated by this code may be loaded by main 
 * programs, or other shared objects, even those with closed source licenses.
 *
 * das2dlm is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 2.1 as published
 * by the Free Software Foundation.
 *
 * das2dlm is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 2.1 along with libdas2; if not, see <http://www.gnu.org/licenses/>.
 */
				
/* Output structure definition */
static IDL_STRUCT_TAG_DEF DAS2C_PROP_tags[] = {
	{"KEY",     NULL,     (void*)IDL_TYP_STRING},
	{"TYPE",    NULL,     (void*)IDL_TYP_STRING},
	{"VALUE",   NULL,     (void*)IDL_TYP_STRING},
	{0}
};

typedef struct das2c_prop_data_s{
	IDL_STRING key;
	IDL_STRING type;
	IDL_STRING value;
} DAS2C_PROP_data;

static IDL_StructDefPtr DAS2C_PROP_pdef;

static void define_DAS2C_PROP()
{
	DAS2C_PROP_pdef = IDL_MakeStruct("DAS2C_PROP", DAS2C_PROP_tags);
}

/* ************************************************************************* */
/* Downstream property function arg handlers */

/* Does not return NULL if:  0 <= iArg < argc */
const char* das2c_args_prop_name(int argc, IDL_VPTR* argv, int iArg)
{
	const char* sName = NULL;
	if(argc <= iArg) return NULL;
	
	if(argv[iArg]->type == IDL_TYP_STRING){
		sName = IDL_VarGetString(argv[iArg]);
		if((sName == NULL)||(*sName == '\0'))
			das2c_IdlMsgExit("Property name argument is empty");
		return sName;
	}

	das2c_IdlMsgExit("Property name argument is not a string");
	return NULL;  /* We never get here, but make compiler happy */
}

/* ************************************************************************* */
/* Return props from a DasDesc (das2 decriptor) object */

/* If key is null, return all properties */
IDL_VPTR das2c_props_from_desc(const DasDesc* pDesc, const char* sKey)
{
	size_t uProps = DasDesc_length(pDesc);
	if(uProps == 0) return IDL_GettmpNULL();
	
	const char* sType = NULL;
	const char* sVal  = NULL;
	
	IDL_MEMINT dims = 1;
	if(sKey != NULL){
		if(!DasDesc_has(pDesc, sKey)) return IDL_GettmpNULL();
		sType = DasDesc_getType(pDesc, sKey);
		sVal =  DasDesc_get(pDesc, sKey);
	}
	else{
		dims = uProps;
	}
	
	IDL_VPTR pRet;
	DAS2C_PROP_data* pData = (DAS2C_PROP_data*) IDL_MakeTempStruct(
		DAS2C_PROP_pdef,   /* The opaque structure definition */
		1,                   /* Number of dimesions */
		&dims,               /* Size of each dimension, (only one dimension) */
		&pRet,               /* The actual structure variable */
		TRUE                 /* Zero out the array */
	);
	
	if(sKey != NULL){
		IDL_StrStore(&(pData->key),   sKey);
		IDL_StrStore(&(pData->type),  sType);
		IDL_StrStore(&(pData->value), sVal);
		return pRet;
	}
	
	/* Here we loop over properites instead, due to the dumb properties 
	 * implementation this is a 3*N^2 operation!! */
	for(size_t u = 0; u < uProps; ++u)
	{
		sKey  = DasDesc_getNameByIdx(pDesc, u);
		sType = DasDesc_getTypeByIdx(pDesc, u);
		sVal  = DasDesc_getValByIdx(pDesc,  u);
		IDL_StrStore(&(pData->key),   sKey);
		IDL_StrStore(&(pData->type),  sType);
		IDL_StrStore(&(pData->value), sVal);
		++pData;
	}
	
	return pRet;
}

/* ************************************************************************* */
/* API Functions, careful with changes! */

#define D2C_PROPS_MINA 1
#define D2C_PROPS_MAXA 2
#define D2C_PROPS_FLAG 0

/*
;+
; FUNCTION:
;  das2c_props
;
; PURPOSE:
;  Get dataset metadata properties
;
; CALLING SEQUENCE:
;  Result = das2c_props(struct)
;  Result = das2c_props(struct, key)
;
; INPUTS:
;  struct: Either a DAS2C_DSET or DAS2C_PDIM structure.
;
; OPTIONAL INPUTS:
;  key: The name of a specific property
;
; OUTPUT:
;  This function returns an array of structures providing the property or
;  properties of the dataset.  Each structure has the following fields
;
;    KEY    String   ; The name of the property
;
;    TYPE   String   ; The intended final data type for the property
;
;    VALUE  String   ; A string version of the property value.
;
;  If a prop key is given as an input but the dataset has no properties with
;  that name, !NULL is returned.  If the dataset has no properites at all,
;  then !NULL is retured when the the full property list is requested.
;
; EXAMPLES:
;  Get all the properties for dataset 1 from query result 48:
;    query = das2c_queries(48)
;    ds = das2c_datasets(query, 1)
;    das2c_dsprops(ds)
;
;  Get the label property for the time dimension from the dataset above:
;    pd_time = das2c_pdims(ds, 'time')
;    das2c_dsprops(pd_time, 'label')
;
; MODIFICATION HISTORY:
;  Written by: Chris Piker, 2020-03-13
;-
*/
static IDL_VPTR das2c_api_props(int argc, IDL_VPTR* argv)
{
	
	int iQuery = -1;
	int iDs = -1;
	const DasDs* pDs = das2c_arg_to_ds(argc, argv, 0, &iQuery, &iDs);
	const DasDim* pDim = NULL;
	const char* sDim = NULL;
	UCHAR* pData = NULL;
	
	const char* sKey = NULL;
	/* See if they want a specific prop or not */
	if(argc > 1){
		sKey = das2c_args_prop_name(argc, argv, 1);
	}
	
	/* Look at the structure and see if it has a PDIM memeber.  We know it
	   has to be a structure because the das2c_arg_to_ds call worked */
	IDL_VPTR pFakeVar = NULL;
	IDL_MEMINT nOffset = IDL_StructTagInfoByName(
		argv[0]->value.s.sdef, 
		"PDIM", 
		IDL_MSG_SUPPRESS /* Just return if no prop */, 
		&pFakeVar
	);
	
	if(pFakeVar != NULL){
		/* Oh, they do have a 'PDIM' member */
		if(pFakeVar->type != IDL_TYP_STRING)
			das2c_IdlMsgExit("Field PDIM in argument1 is not a string");
		
		pData = argv[0]->value.s.arr->data + nOffset;
	
		/* IDL docs are not clear on whos own's the memory after this call
		   https://www.harrisgeospatial.com/docs/StringProcessing.html 
		   Assume they do for now and use valgrind to see for sure later */
		sDim = IDL_STRING_STR( (IDL_STRING*)pData);
		if((sDim == NULL)||(sDim[0] == '\0'))
			das2c_IdlMsgExit("Field PDIM is empty in the structure at argument 1");
		
		pDim = DasDs_getDimById(pDs, sDim);
		if(pDim == NULL)
			das2c_IdlMsgExit(
				"Mismatch PDIM '%s' is not present in query %d, dataset %d",
				sDim, iQuery, iDs
			);
		
		return das2c_props_from_desc((DasDesc*)pDim, sKey);
	}
	else{		
		return das2c_props_from_desc((DasDesc*)pDs, sKey);
	}
}
