/* Copyright (C) 2020 Chris Piker <chris-piker@uiowa.edu>
 *                    
 * This file is part of das2dlm, an Interactive Data Language (IDL) binding
 * for the das2C library.  IDL is a trademark of Harris Geospatial Solutions,
 * Inc.  The shared object generated by this code may be loaded by main 
 * programs, or other shared objects, even those with closed source licenses.
 *
 * das2dlm is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 2.1 as published
 * by the Free Software Foundation.
 *
 * das2dlm is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 2.1 along with libdas2; if not, see <http://www.gnu.org/licenses/>.
 */
 
 
/* ************************************************************************* */
/* API Function, careful with changes! */	

#define D2C_FREE_MINA 1
#define D2C_FREE_MAXA 1
#define D2C_FREE_FLAG 0

/*
;+
; FUNCTION:
;  das2c_free
;
; PURPOSE:
;  Delete resources associated with a single das2 query from memory
;
; CALLING SEQUENCE:
;  Result = das2c_free(query)
;
; INPUTS:
;  query:  An integer query ID, or a DAS2C_QUERY structure as return by
;          das2c_queries() or das2c_readhttp()
;
; OUTPUT:
;   Returns the number of query results still in memory.
;
; SIDE EFFECTS:
;   All structures that have be returned by das2c_datasets, das2c_pdims,
;   and das2c_vars, no longer map to objects in the internal query database.
;   The structures themselves are still valid, but not that useful.
;
;   Any arrays that have been returned by das2c_data are not deleted 
;   automatically if still held in an IDL user space variable.  These are
;   cleaned up IDL itself.
;
; EXAMPLES:
;  List summary information on all physical dimensions for dataset 0 in
;  query result 27:
;    query = das2c_query(27)
;    ds = das2c_datasets(query, 0)
;    das2c_pdims(ds)
;
;  List summary information on the time dimension in the same dataset.
;    das2c_pdims(ds, 'time')
;
; MODIFICATION HISTORY:
;  Written by: Chris Piker, 2020-03-12
;-
*/

static IDL_VPTR das2c_api_free(int argc, IDL_VPTR* argv){
	
	/* If this is a structure, make sure this structure is actually
	   named DAS2C_QUERY */
	if(argc < 1) das2c_IdlMsgExit("Argument 1 is missing");
	
	IDL_VPTR pVar = argv[0];
	IDL_VPTR pFakeVar = NULL;
	IDL_VPTR pTmpVar = NULL;
	char* sStructName = NULL;
	UCHAR* pData = NULL;
	IDL_MEMINT nOffset = 0;
	int32_t iQuery = -1;
	
	if(pVar->type == IDL_TYP_STRUCT){
		IDL_StructTagNameByIndex(
			pVar->value.s.sdef, 0, IDL_MSG_LONGJMP, &sStructName
		);
		if(strcmp("DAS2C_QUERY", sStructName) != 0)
			das2c_IdlMsgExit(
				"Structure type is '%s' expected a DAS2C_QUERY", sStructName
			);
		
		/* Code below is better commented in das2c_arg_to_ent() */
		pFakeVar = NULL;
		nOffset = IDL_StructTagInfoByName(
			pVar->value.s.sdef, "QUERY", IDL_MSG_LONGJMP, &pFakeVar
		);
		
		pData = pVar->value.s.arr->data + nOffset;
		switch(pFakeVar->type){
		case IDL_TYP_INT:  iQuery = *((IDL_INT*)pData);  break;
		case IDL_TYP_UINT: iQuery = *((IDL_UINT*)pData); break;
		case IDL_TYP_LONG: iQuery = *((IDL_LONG*)pData); break;
		/* other types have range larger than uint32_t */
		default:
			das2c_IdlMsgExit(" 'QUERY' value should be an INT, UINT or LONG");
			break;
		}
	}
	else{
		pTmpVar = IDL_BasicTypeConversion(1, argv + 0, IDL_TYP_LONG);
		iQuery = pTmpVar->value.l;
		IDL_DELTMP(pTmpVar);
	}
	
	bool bExisted = das2c_db_free_ent(iQuery);
	if(!bExisted)
		daslog_warn_v("Query ID %d was not present in the result table", iQuery);
	
	return IDL_GettmpLong(g_nDbStored);
}
