/* Copyright (C) 2020 Chris Piker <chris-piker@uiowa.edu>
 *                    
 * This file is part of das2dlm, an Interactive Data Language (IDL) binding
 * for the das2C library.  IDL is a trademark of Harris Geospatial Solutions,
 * Inc.  The shared object generated by this code may be loaded by main 
 * programs, or other shared object, with closed source licenses.
 *
 * das2dlm is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 2.1 as published
 * by the Free Software Foundation.
 *
 * das2dlm is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 2.1 along with libdas2; if not, see <http://www.gnu.org/licenses/>.
 */
 
/* ************************************************************************* */
/* Global structure definitions */

static void* g_pIdlDsDef = NULL;   /* das2 Datasets */
static void* g_pIdlDimDef = NULL;  /* das2 Physical Dimensions */
static void* g_pIdlVarDef = NULL;  /* das2 Variables */

static IDL_STRUCT_TAG_DEF s_dsTags[] = {
	{ "
	
}

static void _das2c_init_struct_defs(){

	
}

/* ************************************************************************* */
/* Convert an array of das datasets to an IDL structure
   
   I'm outputting data as an anoymous structure.  A nested set of hash objects
	would be much more appropriate but this propriatary platform does not allow C
	code to access or return variables of type IDL_TYP_PTR, IDL_TYP_OBJ.  Unlike
	Python, there is a lack of symetry between C code and IDL code as some of
	the IDL internals are hidden.  Yay! 
	
	Since singular strutures do not exist (they are all arrays of structures)
	and since referencing heap memory is not allowed (grrrr) the *exact* size
	of the structure must be known.  To do this we have to build the output from
	the bottom up, in reverse order.
	
	Irritatingly, the resulting object is SET IN STONE and can't be mutated 
	in any useful mananer.  Calling code should find and extract the useful
	parts and dump the original.  --cwp
	
	Arrays:    T-dat-1    F-dat-1    A-dat-1      T-dat-2    F-dat-2    A-dat-2
	
	Props:     T-units-1  F-units-1  A-units-1    T-units-2  F-units-2  A-units-2
	
	PhysDims:   time1      freq1      amp1          time2     freq2       amp-2
	
	struct of N datasets
     |
     Dataset Struct
       |
		(associative array?)
		 |
       Dimension Struct
         |
	     (associative array?)
			|
         Variable Struct
           |
			 (member)
			  |
           Data Array
*/

static IDL_VPTR _das2c_convertOut(DasDs** lDs, size_t uDs)
{
	/* tplot mantains a global set of variable names.  Help it by generating
	   a unique name for each variable. */
	
	/* Dataset stucture definition */
	IDL_StructDefPtr pIdlDefDs = NULL;
	
	IDL_VPTR pIdlDsAry = NULL;
	
	/* Return value is pVec->value.arr->data for some reason */
	char* pData = IDL_MakeTempStructVector(
		pIdlDsDef, (IDL_MEMINT)uDs, &pIdlDsAry, TRUE
	);
	
	
	
	/* Making the sub data arrays */
	IDL_VPTR pAry = IDL_ImportNamedArray(pAry->
		

	char sDsInfo[1024] = {'\0'};
	DasDs_toStr(lDs[u], sDsInfo, 1023);	
}
